# Identifiant unique du projet
sonar.projectKey=portfolio
sonar.projectName=Portfolio FullStack
sonar.projectVersion=1.0

# Dossiers à analyser
sonar.sources=.

# Dossiers à exclure
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/coverage/**

# Encodage
sonar.sourceEncoding=UTF-8

# Backend JavaScript
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info